"""Russian names for countries, cities and well-known airports.

English names come from OurAirports. This overlay is what Russian-speaking
users type and see (Москва, Шереметьево, Турция).
"""

from __future__ import annotations

# ISO 3166-1 alpha-2 -> Russian country name.
COUNTRY_RU: dict[str, str] = {
    "AE": "ОАЭ", "AF": "Афганистан", "AL": "Албания", "AM": "Армения",
    "AO": "Ангола", "AR": "Аргентина", "AT": "Австрия", "AU": "Австралия",
    "AZ": "Азербайджан", "BA": "Босния и Герцеговина", "BD": "Бангладеш",
    "BE": "Бельгия", "BG": "Болгария", "BH": "Бахрейн", "BY": "Беларусь",
    "BO": "Боливия", "BR": "Бразилия", "CA": "Канада", "CH": "Швейцария",
    "CL": "Чили", "CN": "Китай", "CO": "Колумбия", "CR": "Коста-Рика",
    "CU": "Куба", "CY": "Кипр", "CZ": "Чехия", "DE": "Германия",
    "DK": "Дания", "DO": "Доминикана", "DZ": "Алжир", "EC": "Эквадор",
    "EE": "Эстония", "EG": "Египет", "ES": "Испания", "ET": "Эфиопия",
    "FI": "Финляндия", "FR": "Франция", "GB": "Великобритания", "GE": "Грузия",
    "GR": "Греция", "HK": "Гонконг", "HR": "Хорватия", "HU": "Венгрия",
    "ID": "Индонезия", "IE": "Ирландия", "IL": "Израиль", "IN": "Индия",
    "IQ": "Ирак", "IR": "Иран", "IS": "Исландия", "IT": "Италия",
    "JO": "Иордания", "JP": "Япония", "KE": "Кения", "KG": "Киргизия",
    "KH": "Камбоджа", "KR": "Южная Корея", "KW": "Кувейт", "KZ": "Казахстан",
    "LA": "Лаос", "LB": "Ливан", "LK": "Шри-Ланка", "LT": "Литва",
    "LU": "Люксембург", "LV": "Латвия", "MA": "Марокко", "MD": "Молдова",
    "ME": "Черногория", "MK": "Северная Македония", "MN": "Монголия",
    "MT": "Мальта", "MV": "Мальдивы", "MX": "Мексика", "MY": "Малайзия",
    "NG": "Нигерия", "NL": "Нидерланды", "NO": "Норвегия", "NP": "Непал",
    "NZ": "Новая Зеландия", "OM": "Оман", "PE": "Перу", "PH": "Филиппины",
    "PK": "Пакистан", "PL": "Польша", "PT": "Португалия", "QA": "Катар",
    "RO": "Румыния", "RS": "Сербия", "RU": "Россия", "SA": "Саудовская Аравия",
    "SE": "Швеция", "SG": "Сингапур", "SI": "Словения", "SK": "Словакия",
    "TH": "Таиланд", "TJ": "Таджикистан", "TM": "Туркменистан", "TN": "Тунис",
    "TR": "Турция", "TW": "Тайвань", "TZ": "Танзания", "UA": "Украина",
    "US": "США", "UZ": "Узбекистан", "VN": "Вьетнам", "ZA": "ЮАР",
}

# English city (lowercase) -> Russian city. Used for display + search aliases.
CITY_RU: dict[str, str] = {
    "moscow": "Москва", "saint petersburg": "Санкт-Петербург",
    "st petersburg": "Санкт-Петербург", "novosibirsk": "Новосибирск",
    "yekaterinburg": "Екатеринбург", "kazan": "Казань", "nizhny novgorod": "Нижний Новгород",
    "chelyabinsk": "Челябинск", "samara": "Самара", "omsk": "Омск",
    "rostov-on-don": "Ростов-на-Дону", "ufa": "Уфа", "krasnoyarsk": "Красноярск",
    "voronezh": "Воронеж", "perm": "Пермь", "volgograd": "Волгоград",
    "krasnodar": "Краснодар", "saratov": "Саратов", "tyumen": "Тюмень",
    "tolyatti": "Тольятти", "izhevsk": "Ижевск", "barnaul": "Барнаул",
    "irkutsk": "Иркутск", "khabarovsk": "Хабаровск", "yaroslavl": "Ярославль",
    "vladivostok": "Владивосток", "tomsk": "Томск", "kemerovo": "Кемерово",
    "ryazan": "Рязань", "naberezhnye chelny": "Набережные Челны",
    "penza": "Пенза", "lipetsk": "Липецк", "tula": "Тула", "kirov": "Киров",
    "cheboksary": "Чебоксары", "kaliningrad": "Калининград", "bryansk": "Брянск",
    "ivanovo": "Иваново", "magnitogorsk": "Магнитогорск", "kursk": "Курск",
    "tver": "Тверь", "sochi": "Сочи", "adler": "Сочи", "simferopol": "Симферополь",
    "mineralnye vody": "Минеральные Воды", "mineralnye-vody": "Минеральные Воды",
    "anapa": "Анапа", "gelendzhik": "Геленджик", "surgut": "Сургут",
    "nizhnevartovsk": "Нижневартовск", "yakutsk": "Якутск", "magadan": "Магадан",
    "yuzhno-sakhalinsk": "Южно-Сахалинск", "petropavlovsk-kamchatsky": "Петропавловск-Камчатский",
    "murmansk": "Мурманск", "arkhangelsk": "Архангельск", "syktyvkar": "Сыктывкар",
    "grozny": "Грозный", "makhachkala": "Махачкала", "astrakhan": "Астрахань",
    "omsk": "Омск",
    "dushanbe": "Душанбе", "khujand": "Худжанд", "khudzhand": "Худжанд",
    "tashkent": "Ташкент", "samarkand": "Самарканд", "bukhara": "Бухара",
    "namangan": "Наманган", "andijan": "Андижан", "nukus": "Нукус",
    "almaty": "Алматы", "astana": "Астана", "nur-sultan": "Астана",
    "shymkent": "Шымкент", "aktobe": "Актобе", "aktau": "Актау",
    "bishkek": "Бишкек", "osh": "Ош",
    "ashgabat": "Ашхабад", "turkmenbashi": "Туркменбаши",
    "baku": "Баку", "ganja": "Гянджа",
    "tbilisi": "Тбилиси", "batumi": "Батуми", "kutaisi": "Кутаиси",
    "yerevan": "Ереван", "gyumri": "Гюмри",
    "minsk": "Минск", "gomel": "Гомель",
    "chisinau": "Кишинёв", "kishinev": "Кишинёв",
    "kyiv": "Киев", "kiev": "Киев", "odesa": "Одесса", "odessa": "Одесса",
    "lviv": "Львов", "kharkiv": "Харьков",
    "istanbul": "Стамбул", "ankara": "Анкара", "antalya": "Анталья",
    "izmir": "Измир", "bodrum": "Бодрум", "dalaman": "Даламан",
    "dubai": "Дубай", "abu dhabi": "Абу-Даби", "sharjah": "Шарджа",
    "doha": "Доха", "riyadh": "Эр-Рияд", "jeddah": "Джидда",
    "muscat": "Маскат", "kuwait city": "Эль-Кувейт", "bahrain": "Манама",
    "tel aviv": "Тель-Авив", "jerusalem": "Иерусалим", "amman": "Амман",
    "cairo": "Каир", "hurghada": "Хургада", "sharm el sheikh": "Шарм-эль-Шейх",
    "sharm el-sheikh": "Шарм-эль-Шейх", "luxor": "Луксор",
    "london": "Лондон", "manchester": "Манчестер", "edinburgh": "Эдинбург",
    "paris": "Париж", "nice": "Ницца", "lyon": "Лион", "marseille": "Марсель",
    "frankfurt am main": "Франкфурт", "frankfurt": "Франкфурт",
    "orio al serio": "Бергамо", "ferno": "Милан",
    "hamburg": "Гамбург", "dusseldorf": "Дюссельдорф", "cologne": "Кёльн",
    "rome": "Рим", "milan": "Милан", "venice": "Венеция", "naples": "Неаполь",
    "florence": "Флоренция", "bologna": "Болонья",
    "madrid": "Мадрид", "barcelona": "Барселона", "malaga": "Малага",
    "palma de mallorca": "Пальма", "valencia": "Валенсия", "alicante": "Аликанте",
    "lisbon": "Лиссабон", "porto": "Порту",
    "amsterdam": "Амстердам", "brussels": "Брюссель", "vienna": "Вена",
    "zurich": "Цюрих", "geneva": "Женева", "prague": "Прага",
    "budapest": "Будапешт", "warsaw": "Варшава", "krakow": "Краков",
    "athens": "Афины", "thessaloniki": "Салоники", "heraklion": "Ираклион",
    "rhodes": "Родос", "corfu": "Корфу",
    "helsinki": "Хельсинки", "stockholm": "Стокгольм", "oslo": "Осло",
    "copenhagen": "Копенгаген", "reykjavik": "Рейкьявик",
    "dublin": "Дублин", "riga": "Рига", "vilnius": "Вильнюс", "tallinn": "Таллин",
    "bucharest": "Бухарест", "sofia": "София", "belgrade": "Белград",
    "zagreb": "Загреб", "split": "Сплит", "dubrovnik": "Дубровник",
    "ljubljana": "Любляна", "podgorica": "Подгорица", "tirana": "Тирана",
    "new york": "Нью-Йорк", "los angeles": "Лос-Анджелес", "chicago": "Чикаго",
    "miami": "Майами", "san francisco": "Сан-Франциско", "seattle": "Сиэтл",
    "boston": "Бостон", "washington": "Вашингтон", "las vegas": "Лас-Вегас",
    "orlando": "Орландо", "houston": "Хьюстон", "dallas": "Даллас",
    "atlanta": "Атланта", "denver": "Денвер", "toronto": "Торонто",
    "montreal": "Монреаль", "vancouver": "Ванкувер",
    "beijing": "Пекин", "shanghai": "Шанхай", "guangzhou": "Гуанчжоу",
    "hong kong": "Гонконг", "tokyo": "Токио", "osaka": "Осака",
    "seoul": "Сеул", "busan": "Пусан", "taipei": "Тайбэй",
    "bangkok": "Бангкок", "phuket": "Пхукет", "pattaya": "Паттайя",
    "singapore": "Сингапур", "kuala lumpur": "Куала-Лумпур",
    "jakarta": "Джакарта", "bali": "Бали", "denpasar": "Денпасар",
    "manila": "Манила", "ho chi minh city": "Хошимин", "hanoi": "Ханой",
    "delhi": "Дели", "mumbai": "Мумбаи", "bangalore": "Бангалор",
    "goa": "Гоа", "colombo": "Коломбо", "male": "Мале", "kathmandu": "Катманду",
    "sydney": "Сидней", "melbourne": "Мельбурн", "auckland": "Окленд",
    "cape town": "Кейптаун", "johannesburg": "Йоханнесбург",
    "nairobi": "Найроби", "addis ababa": "Аддис-Абеба",
    "mexico city": "Мехико", "cancun": "Канкун", "sao paulo": "Сан-Паулу",
    "rio de janeiro": "Рио-де-Жанейро", "buenos aires": "Буэнос-Айрес",
    "lima": "Лима", "santiago": "Сантьяго",
}

# IATA -> Russian airport name (when it differs from the city).
AIRPORT_RU: dict[str, str] = {
    "SVO": "Шереметьево", "VKO": "Внуково", "DME": "Домодедово", "ZIA": "Жуковский",
    "LED": "Пулково", "AER": "Адлер", "MRV": "Минеральные Воды",
    "LHR": "Хитроу", "LGW": "Гатвик", "STN": "Станстед", "LTN": "Лутон", "LCY": "Сити",
    "CDG": "Шарль-де-Голль", "ORY": "Орли",
    "JFK": "Джон Кеннеди", "LGA": "Ла-Гуардия", "EWR": "Ньюарк",
    "ORD": "О’Хара", "MDW": "Мидуэй",
    "NRT": "Нарита", "HND": "Ханеда",
    "PEK": "Столичный", "PKX": "Дасин",
    "ICN": "Инчхон", "GMP": "Гимпхо",
    "DXB": "Международный", "DWC": "Аль-Мактум",
    "IST": "Стамбул", "SAW": "Сабиха Гёкчен",
    "MXP": "Мальпенса", "LIN": "Линате", "BGY": "Бергамо",
    "FCO": "Фьюмичино", "CIA": "Чампино",
    "MAD": "Барахас", "BCN": "Эль-Прат",
    "FRA": "Франкфурт", "MUC": "Мюнхен", "BER": "Бранденбург",
    "AMS": "Схипхол", "VIE": "Швехат", "ZRH": "Клотен",
    "DOH": "Хамад", "SIN": "Чанги", "HKG": "Чхеклапкок",
    "BKK": "Суварнабхуми", "DMK": "Донмыанг",
    "KUL": "Куала-Лумпур", "CGK": "Сукарно-Хатта", "DPS": "Нгура-Рай",
    "DEL": "Индира Ганди", "BOM": "Чхатрапати Шиваджи",
    "SYD": "Кингсфорд Смит", "MEL": "Талламарин",
    "GRU": "Гуарульюс", "GIG": "Галеан",
    "EZE": "Эсейса", "AEP": "Хорхе Ньюбери",
    "YYZ": "Пирсон", "YVR": "Ванкувер",
    "LBD": "Худжанд", "DYU": "Душанбе", "TAS": "Ташкент",
    "SKD": "Самарканд", "ALA": "Алматы", "NQZ": "Назарбаев", "TSE": "Назарбаев",
    "FRU": "Манас", "GYD": "Гейдар Алиев", "TBS": "Тбилиси", "EVN": "Звартноц",
    "MSQ": "Минск", "KBP": "Борисполь", "MMK": "Мурманск",
}

# IATA -> Russian city (when OurAirports municipality is a suburb / English dump).
CITY_BY_IATA: dict[str, str] = {
    "MXP": "Милан", "LIN": "Милан", "BGY": "Милан",
    "CDG": "Париж", "ORY": "Париж", "BVA": "Париж",
    "LHR": "Лондон", "LGW": "Лондон", "STN": "Лондон", "LTN": "Лондон", "LCY": "Лондон",
    "JFK": "Нью-Йорк", "LGA": "Нью-Йорк", "EWR": "Нью-Йорк",
    "MMK": "Мурманск", "FRA": "Франкфурт",
}
ALIASES: dict[str, str] = {
    "мск": "MOW", "moscow": "MOW", "moskva": "MOW",
    "питер": "LED", "спб": "LED", "spb": "LED", "петербург": "LED",
    "нск": "OVB", "екб": "SVX", "кзн": "KZN",
    "худж": "LBD", "худжанд": "LBD", "khujand": "LBD",
    "тошкент": "TAS", "ташкент": "TAS",
    "алма-ата": "ALA", "алмата": "ALA",
    "стамбул": "IST", "дубаи": "DXB", "дубай": "DXB",
    "адлер": "AER", "сочи": "AER",
    "хитроу": "LHR", "гатвик": "LGW",
    "шенген": "CDG",  # common miss; still useful as Paris hint via CDG
    "нью йорк": "NYC", "нью-йорк": "NYC", "ньюйорк": "NYC",
    "лондон": "LON", "париж": "PAR", "рим": "ROM", "милан": "MIL",
    "барселона": "BCN", "мадрид": "MAD", "берлин": "BER",
    "токио": "TYO", "пекин": "BJS", "сеул": "SEL",
    "бангкок": "BKK", "пхукет": "HKT",
    "мурманск": "MMK",
}

# Cities with several airports: metro code -> IATA list (specific airports).
METROS: dict[str, tuple[str, ...]] = {
    "MOW": ("SVO", "VKO", "DME", "ZIA"),
    "NYC": ("JFK", "LGA", "EWR"),
    "LON": ("LHR", "LGW", "STN", "LTN", "LCY"),
    "PAR": ("CDG", "ORY", "BVA"),
    "MIL": ("MXP", "LIN", "BGY"),
    "ROM": ("FCO", "CIA"),
    "STO": ("ARN", "BMA", "NYO", "VST"),
    "BUE": ("EZE", "AEP"),
    "BJS": ("PEK", "PKX"),
    "SEL": ("ICN", "GMP"),
    "TYO": ("HND", "NRT"),
    "WAS": ("IAD", "DCA", "BWI"),
    "YTO": ("YYZ", "YTZ", "YHM"),
    "SAO": ("GRU", "CGH", "VCP"),
    "RIO": ("GIG", "SDU"),
    "CHI": ("ORD", "MDW"),
}


def country_ru(cc: str, fallback: str = "") -> str:
    return COUNTRY_RU.get(cc.upper(), fallback or cc)


def city_ru(city_en: str, fallback: str = "") -> str:
    return CITY_RU.get((city_en or "").strip().lower(), fallback or city_en)


def airport_ru(code: str, fallback: str = "") -> str:
    return AIRPORT_RU.get((code or "").upper(), fallback)
